### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating numpy array `

C:\Users\CHETNA GURURANI\AppData\Local\Temp\ipykernel_2516\28058047.py:1: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML


In [1]:
# np.array
import numpy as np

In [11]:
# create a numpy array using np.array
a=np.array([1, 2, 3]) # can also be called as vector
print(type(a))

<class 'numpy.ndarray'>


In [19]:
# 2D and 3D array
b= np.array([[1, 2, 3],[4,5,6]]) # also called as matrix
print(b)

[[1 2 3]
 [4 5 6]]


In [27]:
# 3D 
c= np.array([[[1, 3],[4,6]], [[3, 5] ,[0, 6]]]) # also called as Tesor
print(c)

[[[1 3]
  [4 6]]

 [[3 5]
  [0 6]]]


In [ ]:
# DATA TYPE IN NP.ARRAY

In [29]:
# float datatype array
np.array([1,2, 3], dtype=float)

array([1., 2., 3.])

In [33]:
np.array([1,2, 3], dtype=bool) # ever non zero value = True

array([ True,  True,  True])

In [35]:
np.array([2, 4, 5], dtype= complex)

array([2.+0.j, 4.+0.j, 5.+0.j])

<b> np.arange
- Another way to create a array of range

In [38]:
np.arange(1, 11) # just like range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
# slide
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

<b>np.arange().reshape()

In [46]:
# with reshape
np.arange(1,11).reshape(5, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [5]:
import numpy as np
np.arange(1, 25).reshape(4, 2, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [52]:
np.arange(1,9).reshape(4, 2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

<b> no.ones and np.zeros

In [63]:
np.ones((3,4)) # Used for initialization

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [65]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

<b> np.random

In [68]:
np.random.random((3, 4)) # give random number between them

array([[0.39622489, 0.91096849, 0.64423777, 0.19169011],
       [0.44426052, 0.73716205, 0.03187231, 0.11514407],
       [0.51993323, 0.09431332, 0.67716604, 0.55327317]])

<b> np.linshape(linearly space)
- in generate linearly seperable space
- used in plot ML algo graph

In [5]:
np.linspace(-10, 10, 10) # (lower range, upper range, number of items you want to generate)
# used in plot ML algo graph

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

<b> np.identity
- create identity matrix whose digonal item are 1 and rest are 0

In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Array Attribute

In [9]:
a1= np.arange(10, dtype=np.int32)
a2= np.arange(12, dtype=float).reshape(3,4) # matrix
a3= np.arange(8).reshape(2,2,2) # tensor
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [16]:
# ndim - tell about what is the dimension array
a3.ndim

3

In [13]:
# shape - tell about dimension in array
print(a1.shape)
print(a2.shape)
print(a3.shape)# (number of 2D array, number of row and column)

(10,)
(3, 4)
(2, 2, 2)


In [19]:
# size: total number of element in array
a3.size
a2.size 

12

In [21]:
# itemsize
print(a1.itemsize)
print(a2.itemsize)  #  (size of datatype in a array)

4

In [23]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


### Changing Data type

In [11]:
# astype- changing the datatype (Eg: int64- to - int34(to occupy less memory)
a3.dtype
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

### Array Operation
- to run mathematical operation in an array

In [5]:
a1= np.arange(12).reshape(3,4)
a2= np.arange(12,24).reshape(3,4)

In [53]:
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


<b> Scalar operations

In [ ]:
# arithmetic

# perform all arithmetic operation
print(a1/2)
print(a2*5)
a1 ** 2 # vector * scalar

In [67]:
# relationship

print(a1>15)

print(a2==12)

[[False False False False]
 [False False False False]
 [False False False False]]
[[ True False False False]
 [False False False False]
 [False False False False]]


#### vector operation 
- shape should be same

In [72]:
# arithmatic
a1+ a2 # since the shape was same

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [74]:
a1 ** a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

#### Array of function

In [15]:
a1 = np.random.random((3, 3))
a1= np.round(a1*1000)
a1

array([[828.,   1., 741.],
       [ 75., 865., 280.],
       [804., 705., 711.]])

In [84]:
# max/min/sum/prod
print(np.max(a1))
print(np.min(a2))
print(np.sum(a1))
print(np.prod(a1))

70.0
12
333.0
32248932408000.0


In [90]:
# For row wise operation
# 0 -> col 1-> row
print(np.max(a1, axis=1))
print(np.min(a1, axis=0))
print(np.sum(a2, axis =1))

[45. 70. 55.]
[ 9. 29. 17.]
[54 70 86]


In [94]:
# median/ mean/std/var
print(np.mean(a1))
print(np.mean(a1, axis=0))

37.0
[41.33333333 40.66666667 29.        ]


In [96]:
print(np.std(a1))
print(np.var(a1)) # variance

18.184242262647807
330.6666666666667


In [98]:
# tigometric functions
np.sin(a1)
np.tan(a1)

array([[  1.61977519,   0.88714284,  -2.1348967 ],
       [  1.22195992,   0.31030966,  -2.08661353],
       [ -0.45231566, -45.18308791,   3.49391565]])

In [104]:
# Dot product ( rule 1 matrix column = 2 matrix row )
a3= np.arange(12).reshape(4,3)
a4= np.arange(24).reshape(6, 4)

In [110]:
# np.dot(a3, a4) 
np.dot(a4, a3)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262],
       [258, 312, 366],
       [330, 400, 470],
       [402, 488, 574]])

In [7]:
# log and exponential
print(np.exp(a1))
print(np.log(a2))

[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]
[[2.48490665 2.56494936 2.63905733 2.7080502 ]
 [2.77258872 2.83321334 2.89037176 2.94443898]
 [2.99573227 3.04452244 3.09104245 3.13549422]]


In [3]:
# round /floor /cell
# np.random.random((3,2)) # this will generate a array of 3*2 random number
print(np.round(np.random.random((2, 3))*100) )# multiply it by scalar # this will round of the number
print(np.floor(np.random.random((2,3))*100))

[[71. 15.  3.]
 [52. 54. 21.]]
[[95. 49. 19.]
 [61. 79. 72.]]


### Indexing and slicing

In [8]:
a1= np.arange(10)
a2= np.arange(12).reshape(3,4)
a3= np.arange(8).reshape(2, 2, 2)


In [12]:
a1 # if we want to fetch last time

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
print(a1[-1])
print(a1[0])

9
0


In [18]:
# in 2D array indexing
a2 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
a2[1, 2 ] # [Row,column]

6

In [28]:
a2[2,3]

11

In [30]:
# 3D indexing
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [32]:
a3[1,0,1]#[ which 2D array, Row , column]

5

In [36]:
# fetch 2
a3[0,1, 0]

2

In [40]:
a3[0,0,0]
a3[1,1,0]

6

#### slicing :
- to fetch multiple items

In [43]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
# 2 to 4
print(a1[2:5])
print(a1[2:7:2])

[2 3 4]
[2 4 6]


In [49]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
# To fetch all the element is 1 row
a2[0,:]

array([0, 1, 2, 3])

In [58]:
# to fetch all column in 3rd column
a2[:, 2]

array([ 2,  6, 10])

In [60]:
# if we want 0, 8, 3, 11
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [70]:
a2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [66]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
a2[1,::3]

array([4, 7])

In [76]:
a2[:2,1::2] # row column

array([[1, 3],
       [5, 7]])

In [78]:
# 3D 
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [80]:
a3= np.arange(27).reshape(3,3,3)

In [82]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [88]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [94]:
a3[0,1]

array([3, 4, 5])

In [98]:
a3[1, :, 1]

array([10, 13, 16])

In [102]:
a3[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

In [104]:
a3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

##### Iterating

In [115]:
print(a1)
for i in a1:
    print(i)

[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9


In [119]:
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [121]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
print(a3)

In [123]:
for i in (a3):
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


<b> np.nditer()
- it convert the N dimension array to 1D

In [125]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


 #### Reshaping

In [139]:
# reshaping
a3 = np.arange(27).reshape(3,3,3)

In [17]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [19]:
# Transpose
np.transpose(a2)

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [143]:
# Or You can use
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [137]:
# Ravel : It convert N dimension array into 1D array
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

#### Stacking
- changing in original 
- To join 2 array
-  To join multiple sources, come from various resourse

In [147]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [151]:
np.hstack((a4,a5)) # input is give into the tuple form

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [153]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### Splitting
- opposite of stacking

In [27]:
# horizontal stacking
#                  |
# [ 0,  1,  2,  3, | 12, 13, 14, 15],
# [ 4,  5,  6,  7, | 16, 17, 18, 19],
# [ 8,  9, 10, 11, | 20, 21, 22, 23]
#   
a4 = np.arange(12).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
# horizontal splitting
np.hsplit(a4,2) #dividing in 2 part

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [162]:
# vertical splitting
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [33]:
np.hsplit(a4,2) # cannot divide in 2 parts

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]